### ISSUE TITLE
Missing webpack dev package

### ISSUE THREAD

**Issue by dfranco** [alexandergknoll/php-boilerplate#17]
In order to run "npm run dev", I had to manually install webpack dev npm package

`npm install webpack-dev-server`

The Readme may need to be updated by adding

> For dev, run this command
> `npm install --dev`

**Comment by alexandergknoll** [comment]
@dfranco thank you for checking this out and for the report.

I pulled down a clean version of the repository and ran only `npm install` and that seemed to install all of the dependencies and devDependencies including `webpack-dev-server` so I am wondering if it's a difference in configuration for npm.

From the [npm-install documentation](https://docs.npmjs.com/cli/v9/commands/npm-install), this might be relevant:

> With the `--production` flag (or when the `NODE_ENV` environment variable is set to `production`), npm will not install modules listed in `devDependencies`. To install all modules listed in both `dependencies` and `devDependencies` when `NODE_ENV` environment variable is set to `production`, you can use `--production=false`.

One thing you could try is pulling down a clean version of the repo and running `npm install --production=false` to explicity set production mode to false.  Also if you run `npm config list` you may be able to see if NODE_ENV is being set to production by a configuration file somewhere such as `.npmrc`

**Comment by dfranco** [comment]
Thanks for your feedback, I'll have a try later this week

**Comment by dfranco** [comment]
@alexandergknoll I confirm it works starting from a clean clone of repo.

Thanks again for your help
